### PR TITLE
#165819922 Implement Landing Page

### PR DESCRIPTION
**Pull request by patrickf949**
#### What does this PR do?
Implements landing page for Authors Haven

#### Description of Task to be completed?
- Edit the landing page to contain buttons for the login and signup
- Add articles for the backend api
- Style the landing page according to the mockups

#### How can this be tested?
Install all dependencies

- `$ npm install`

Start the server

- `$ npm start`

Checkout the landing page that appears  in your browser and click the Sign in button in the top right corner.

#### Screen shots:

Landing Page

Screenshot 2019-05-10 at 08 21 22

#### Relevant Pivotal Tracker Stories:
[165819922](https://www.pivotaltracker.com/story/show/165819922)

### CODE REVIEW

**Review by anyatibrian — APPROVED** [review]
LGTM @patrickf949 greate work

**Review by e-ian — APPROVED** [review]
Nicely done @patrickf949. LGTM

**Review by MuhanguziDavid — CHANGES_REQUESTED** [review]
Nice work @patrickf949 , please
- update your commit footer to `Finishes` instead of `Maintains`
- Work on coverage, it should be higher than that

**Comment by patrickf949** [comment]
> Nice work @patrickf949 , please
> 
> * update your commit footer to `Finishes` instead of `Maintains`
> * Work on coverage, it should be higher than that

Thanks @MuhanguziDavid , all done

**Review by MuhanguziDavid — APPROVED** [review]
LGTM

**Pull request merged**
