### PR TITLE
#164798254 Social-authentication using google and facebook

### PR DESCRIPTION
**Pull request by Genza999**
**What does this PR do?**
    Implements functionality of users being able to login using facebook and google

**Description of tasks to be completed**

- install react-facebook-login and react-google-login modules

- create a social authentication component using redux

- Access the backend API's to log in a user into the system

**How should this be manually tested?**
   -  Visit the login page
   - Click on either google or facebook to log into the system using your social media account
   - If successful, a toast will appear informing the user of their successful authentication and login into 
      the system
   - User will be navigated to the home page

**Any background context**

**Screenshots**

   - Google Authentication
   
   - On the  login page, click on the **LOGIN WITH GOOGLE** button:

Screen Shot 2019-05-12 at 22 59 16

   - Choose an account from the Google accounts dialog:

Screen Shot 2019-05-09 at 17 02 05

  - If successful, you are logged in and redirected to the home page:

Screen Shot 2019-05-12 at 22 59 44

     
**What are the relevant pivotal tracker stories**
    [#164798254](https://www.pivotaltracker.com/story/show/164798254)

### CODE REVIEW

**Comment by e-ian** [comment]
@Genza999 Kindly make sure your branch deploys to heroku.

**Review by patrickf949 — APPROVED** [review]
Tested. Great work @Genza999

**Review by anyatibrian — APPROVED** [review]
@Genza999, great work, I really liked your **implementation**

**Review by e-ian — APPROVED** [review]
Good work @Genza999 . LGTM

**Review by MuhanguziDavid — COMMENTED** [review]
Please, resolve merge conflicts

**Comment by Genza999** [comment]
> Please, resolve merge conflicts

Merge conflicts resolved!

**Review by MuhanguziDavid — CHANGES_REQUESTED** [review]
Great work @Genza999 , signin with Google works properly, however, I get this when I try to sign in with Facebook. Please look into it.

Screen Shot 2019-05-13 at 15 21 19

**Comment by Genza999** [comment]
> Great work @Genza999 , signin with Google works properly, however, I get this when I try to sign in with Facebook. Please look into it.
> 
> Screen Shot 2019-05-13 at 15 21 19

Hey, @MuhanguziDavid , this has been fixed. Once successfully authenticated using Facebook, the user now is automatically logged into the system

**Review by MuhanguziDavid — COMMENTED** [review]
Nice work fixing the facebook issue, however, the loader that was added by @e-ian in his task for logging users seems to have been broken. Please fix it.
Also, style the social auth buttons as specified in the mockups i.e.
- Change the font colour to black
- centre align them contents on the buttons
- Use the same font as the rest of the form

**Comment by Genza999** [comment]
> Nice work fixing the facebook issue, however, the loader that was added by @e-ian in his task for logging users seems to have been broken. Please fix it.
> Also, style the social auth buttons as specified in the mockups i.e.
> 
> * Change the font colour to black
> * centre align them contents on the buttons
> * Use the same font as the rest of the form

Hey @MuhanguziDavid , Thanks for pointing out these issues. I have fixed them now.

**Review by MuhanguziDavid — APPROVED** [review]
LGTM

**Pull request merged**
