### PR TITLE
#164798245 Set up environment for testing

### PR DESCRIPTION
**Pull request by Genza999**
**What does this PR do?**
    

- Setting up testing environment

**Description of the tasks to be completed?**

- Install testing dependencies i.e. jest and enzyme

- Configure enzyme adapter

- Create jest.config.js file and define jest configurations

- Write test for existing code in the project

**How should this be manually tested?**

- Clone this repo :
   `git clone ah-frontend-prime`

- Git checkout to this branch :
   `git checkout ch-setup-testing-environment-164798245`

- Install all dependencies :
   `npm install `

- Run tests and coverage:
   `npm test`

**What are the relevant pivot tracker stores?**

- [#164798245](https://www.pivotaltracker.com/story/show/164798245)

**Screenshots**

Screen Shot 2019-04-29 at 20 24 37

### CODE REVIEW

**Review by e-ian — APPROVED** [review]
Neatly done. LGTM

**Review by patrickf949 — APPROVED** [review]
LGTM

**Review by anyatibrian — APPROVED** [review]
great work, @Genza999

**Review by MuhanguziDavid — COMMENTED** [review]
Nice work @Genza999 , however, ensure that your commit message, PR title and description follow the engineering playbook conventions e.g.
- the title of the PR doesn't have to have a colon
- the only upper case letter in the commit should be in the footer i.e. Finishes
- use `chore` instead of `ch`.
[Engineering playbook conventions](https://github.com/andela/engineering-playbook/tree/e654a2dd79972dfe51a1b54d6c7ebc04d2c5e012/5.%20Developing/Conventions#branch-naming)

**Comment by Genza999** [comment]
> Nice work @Genza999 , however, ensure that your commit message, PR title and description follow the engineering playbook conventions e.g.
> 
> * the title of the PR doesn't have to have a colon
> * the only upper case letter in the commit should be in the footer i.e. Finishes
> * use `chore` instead of `ch`.
>   [Engineering playbook conventions](https://github.com/andela/engineering-playbook/tree/e654a2dd79972dfe51a1b54d6c7ebc04d2c5e012/5.%20Developing/Conventions#branch-naming)

Hey @MuhanguziDavid , thanks! I have worked on the feedback.

**Pull request merged**
