### PR TITLE
#164798260 Users can like or dislike articles

### PR DESCRIPTION
**Pull request by Genza999**
**What does this PR do?**
  Creates functionality for users to like or dislike articles

**Description of tasks to be completed**
   

- Create like and dislike buttons for the articles view page

- Write tests for the like/dislike functionality

- Create a view to see the number of users that like/dislike an article

**How can this be tested?**

- Clone the repo

- Checkout ft-users-can-like-dislike-164798260

- npm install && npm start

- log in with your account credentials and get redirected to the homepage upon successful login.

- On the home page, click on one of the articles to full view it. On the articles-view page, below the body of the article are like and dislike buttons in the form of thumbs up for like and thumbs down for dislike. Beside the buttons are the number of users who have so far liked or disliked an article.

- Click on the thumbs up to like the article or thumbs down to dislike the article.

**Screenshots**

Screen Shot 2019-05-22 at 22 41 46

**Relevant Pivotal Tracker stories**
    [#164798260](https://www.pivotaltracker.com/story/show/164798260)

### CODE REVIEW

**Review by anyatibrian — APPROVED** [review]
great work @Genza999

**Review by patrickf949 — APPROVED** [review]
Tested LGTM

**Review by e-ian — APPROVED** [review]
LGTM

**Review by MuhanguziDavid — COMMENTED** [review]
Awesome work @Genza999 , please add toasts to ensure that a user gets feedback when they like, dislike, remove their like, and remove their dislike.

**Comment by Genza999** [comment]
> Awesome work @Genza999 , please add toasts to ensure that a user gets feedback when they like, dislike, remove their like, and remove their dislike.

Hey @MuhanguziDavid , with the current implementation of the likes/dislikes feature in the backend, it may be an issue to effectively implement toasts for the user actions(like, dislike, unlike and un-dislike). However, the likes/dislikes feature works as expected as users can likes/dislike or unlike/un-dislike an article while viewing the total number of users that like/dislike the particular article in real time.

**Review by MuhanguziDavid — APPROVED** [review]
Nice implementation of the likes and dislikes. The toasts could be added at a future date when the backend is fixed.

**Pull request merged**
